apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
        - name: backend
          image: host.docker.internal:8082/labo3/backend-test:latest
          ports:
            - containerPort: 3000
          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: USERNAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: API_KEY
      imagePullSecrets:
        - name: nexus-creds
