apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  USERNAME: "cgma"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  API_KEY: "qwerty012345"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prueba-devops
  template:
    metadata:
      labels:
        app: prueba-devops
    spec:
      containers:
        - name: prueba-devops
          image: cesar-monges/prueba-devops:latest
          ports:
            - containerPort: 3000
          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USERNAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: prueba-devops-service
spec:
  selector:
    app: prueba-devops
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
